; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:Chrono]
platform = atmelsam
board = adafruit_trinket_m0
framework = arduino
build_src_filter = +<./Chrono/*>+<./MEDIC_Comms/MEDIC_Comms*>
lib_deps = 
	greiman/DigitalIO@^1.0.1
	adafruit/Adafruit GFX Library@^1.12.4
	adafruit/Adafruit SSD1306@^2.5.16
	mathertel/RotaryEncoder@^1.6.0
	adafruit/Adafruit ILI9341@^1.6.3
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2

[env:FireControl]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
lib_deps = 
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
build_src_filter = +<./FireControl/*>+<./MEDIC_Comms/MEDIC_Comms*>

[env:Controller]
platform = atmelavr
board = feather32u4
framework = arduino
lib_deps = 
	greiman/DigitalIO@^1.0.1
	adafruit/Adafruit GFX Library@^1.12.4
	mathertel/RotaryEncoder@^1.6.0
	adafruit/Adafruit ILI9341@^1.6.3
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
build_src_filter = +<./Controller/*>+<./MEDIC_Comms/*>+<./FireControl/FireControlStructsEnums.h>

[env:commTest]
platform = atmelavr
board = sparkfun_promicro16
framework = arduino
build_src_filter = +<./commTest/*>+<./FireControl/FireControlStructsEnums.h>+<./MEDIC_Comms/MEDIC_Comms*>
lib_deps = 
	greiman/DigitalIO@^1.0.1
	adafruit/Adafruit GFX Library@^1.12.4
	adafruit/Adafruit SSD1306@^2.5.16
	mathertel/RotaryEncoder@^1.6.0
	adafruit/Adafruit ILI9341@^1.6.3
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
